---
  - name: Sobe o serviço de iptables na máquina security.
    hosts: security
    roles:
      - iptables
    tags:
      - iptables

  - name: Sobe o serviço bind nos servidores web
    hosts: web
    roles:
      - dns
    tags:
      - dns

  - name: Sobe serviço ldap
    hosts: storage
    roles:
      - ldap
    tags:
      - ldap
